# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# If you have issues with plugins that require a higher iOS deployment target, uncomment the following line.
# platform :ios, '13.0'

flutter_application_path = File.expand_path('..', __FILE__)
load File.join(flutter_application_path, '.flutter-plugins-dependencies')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pod
  install_all_flutter_pods File.dirname(File.realpath(__FILE__))

end
